abbrs = {
	"MMM": "3M",
	"ABT": "Abbott Laboratories",
	"ABBV": "AbbVie",
	"ABMD": "Abiomed",
	"ACN": "Accenture",
	"ATVI": "Activision Blizzard",
	"ADBE": "Adobe",
	"AMD": "Advanced Micro Devices",
	"AAP": "Advance Auto Parts",
	"AES": "AES Corp",
	"AFL": "Aflac",
	"A": "Agilent Technologies",
	"APD": "Air Products & Chemicals",
	"AKAM": "Akamai Technologies",
	"ALK": "Alaska Air Group",
	"ALB": "Albemarle Corporation",
	"ARE": "Alexandria Real Estate Equities",
	"ALXN": "Alexion Pharmaceuticals",
	"ALGN": "Align Technology",
	"ALLE": "Allegion",
	"LNT": "Alliant Energy",
	"ALL": "Allstate Corp",
	"GOOGL": "Alphabet (Class A)",
	"GOOG": "Alphabet (Class C)",
	"MO": "Altria Group",
	"AMZN": "Amazon",
	"AMCR": "Amco",
	"AEE": "Ameren Corp",
	"AAL": "American Airlines Group",
	"AEP": "American Electric Power",
	"AXP": "American Express",
	"AIG": "American International Group",
	"AMT": "American Tower",
	"AWK": "American Water Works",
	"AMP": "Ameriprise Financial",
	"ABC": "AmerisourceBergen",
	"AME": "Ametek",
	"AMGN": "Amgen",
	"APH": "Amphenol Corp",
	"ADI": "Analog Devices",
	"ANSS": "Ansys",
	"ANTM": "Anthem",
	"AON": "Aon",
	"AOS": "AO Smith",
	"APA": "APA Corporation",
	"AAPL": "Apple",
	"AMAT": "Applied Materials",
	"APTV": "Aptiv",
	"ADM": "ADM",
	"ANET": "Arista Networks",
	"AJG": "Arthur J. Gallagher & Co.",
	"AIZ": "Assurant",
	"T": "AT&T",
	"ATO": "Atmos Energy",
	"ADSK": "Autodesk",
	"ADP": "Automatic Data Processing",
	"AZO": "AutoZone",
	"AVB": "AvalonBay Communities",
	"AVY": "Avery Dennison",
	"BKR": "Baker Hughes",
	"BLL": "Ball Corp",
	"BAC": "Bank of America",
	"BK": "BNY Mellon",
	"BAX": "Baxter International",
	"BDX": "Becton Dickinson",
	"BRK.B": "Berkshire Hathaway",
	"BBY": "Best Buy",
	"BIO": "Bio-Rad Laboratories",
	"BIIB": "Biogen",
	"BLK": "BlackRock",
	"BA": "Boeing Company",
	"BKNG": "Booking Holdings",
	"BWA": "BorgWarner",
	"BXP": "Boston Properties",
	"BSX": "Boston Scientific",
	"BMY": "Bristol-Myers Squibb",
	"AVGO": "Broadcom",
	"BR": "Broadridge Financial Solutions",
	"BF.B": "Brown-Forman",
	"CHRW": "C. H. Robinson",
	"COG": "Cabot Oil & Gas",
	"CDNS": "Cadence Design Systems",
	"CZR": "Caesars Entertainment",
	"CPB": "Campbell Soup",
	"COF": "Capital One Financial",
	"CAH": "Cardinal Health",
	"KMX": "CarMax",
	"CCL": "Carnival Corporation",
	"CARR": "Carrier Global",
	"CTLT": "Catalent",
	"CAT": "Caterpillar",
	"CBOE": "Cboe Global Markets",
	"CBRE": "CBRE",
	"CDW": "CDW",
	"CE": "Celanese",
	"CNC": "Centene Corporation",
	"CNP": "CenterPoint Energy",
	"CERN": "Cerner",
	"CF": "CF Industries",
	"CRL": "Charles River Laboratories",
	"SCHW": "Charles Schwab Corporation",
	"CHTR": "Charter Communications",
	"CVX": "Chevron Corporation",
	"CMG": "Chipotle Mexican Grill",
	"CB": "Chubb",
	"CHD": "Church & Dwight",
	"CI": "Cigna",
	"CINF": "Cincinnati Financial",
	"CTAS": "Cintas Corporation",
	"CSCO": "Cisco Systems",
	"C": "Citigroup",
	"CFG": "Citizens Financial Group",
	"CTXS": "Citrix Systems",
	"CLX": "Clorox",
	"CME": "CME Group",
	"CMS": "CMS Energy",
	"KO": "Coca-Cola Company",
	"CTSH": "Cognizant Technology Solutions",
	"CL": "Colgate-Palmolive",
	"CMCSA": "Comcast",
	"CMA": "Comerica",
	"CAG": "Conagra Brands",
	"COP": "ConocoPhillips",
	"ED": "Consolidated Edison",
	"STZ": "Constellation Brands",
	"COO": "The Cooper Companies",
	"CPRT": "Copart",
	"GLW": "Corning",
	"CTVA": "Corteva",
	"COST": "Costco",
	"CCI": "Crown Castle",
	"CSX": "CSX",
	"CMI": "Cummins",
	"CVS": "CVS Health",
	"DHI": "D. R. Horton",
	"DHR": "Danaher Corporation",
	"DRI": "Darden Restaurants",
	"DVA": "DaVita",
	"DE": "Deere & Co.",
	"DAL": "Delta Air Lines",
	"XRAY": "Dentsply Sirona",
	"DVN": "Devon Energy",
	"DXCM": "DexCom",
	"FANG": "Diamondback Energy",
	"DLR": "Digital Realty Trust",
	"DFS": "Discover Financial Services",
	"DISCA": "Discovery (Series A)",
	"DISCK": "Discovery (Series C)",
	"DISH": "Dish Network",
	"DG": "Dollar General",
	"DLTR": "Dollar Tree",
	"D": "Dominion Energy",
	"DPZ": "Domino's Pizza",
	"DOV": "Dover Corporation",
	"DOW": "Dow",
	"DTE": "DTE Energy",
	"DUK": "Duke Energy",
	"DRE": "Duke Realty Corp",
	"DD": "DuPont",
	"DXC": "DXC Technology",
	"EMN": "Eastman Chemical",
	"ETN": "Eaton Corporation",
	"EBAY": "eBay",
	"ECL": "Ecolab",
	"EIX": "Edison International",
	"EW": "Edwards Lifesciences",
	"EA": "Electronic Arts",
	"EMR": "Emerson Electric Company",
	"ENPH": "Enphase Energy",
	"ETR": "Entergy",
	"EOG": "EOG Resources",
	"EFX": "Equifax",
	"EQIX": "Equinix",
	"EQR": "Equity Residential",
	"ESS": "Essex Property Trust",
	"EL": "Estée Lauder Companies",
	"ETSY": "Etsy",
	"EVRG": "Evergy",
	"ES": "Eversource Energy",
	"RE": "Everest Re",
	"EXC": "Exelon",
	"EXPE": "Expedia Group",
	"EXPD": "Expeditors",
	"EXR": "Extra Space Storage",
	"XOM": "ExxonMobil",
	"FFIV": "F5 Networks",
	"FB": "Facebook",
	"FAST": "Fastenal",
	"FRT": "Federal Realty Investment Trust",
	"FDX": "FedEx",
	"FIS": "Fidelity National Information Services",
	"FITB": "Fifth Third Bancorp",
	"FE": "FirstEnergy",
	"FRC": "First Republic Bank",
	"FISV": "Fiserv",
	"FLT": "Fleetcor",
	"FMC": "FMC Corporation",
	"F": "Ford",
	"FTNT": "Fortinet",
	"FTV": "Fortive",
	"FBHS": "Fortune Brands Home & Security",
	"FOXA": "Fox Corporation (Class A)",
	"FOX": "Fox Corporation (Class B)",
	"BEN": "Franklin Resources",
	"FCX": "Freeport-McMoRan",
	"GPS": "Gap",
	"GRMN": "Garmin",
	"IT": "Gartner",
	"GNRC": "Generac Holdings",
	"GD": "General Dynamics",
	"GE": "General Electric",
	"GIS": "General Mills",
	"GM": "General Motors",
	"GPC": "Genuine Parts",
	"GILD": "Gilead Sciences",
	"GL": "Globe Life",
	"GPN": "Global Payments",
	"GS": "Goldman Sachs",
	"GWW": "WW Grainger",
	"HAL": "Halliburton",
	"HBI": "Hanesbrands",
	"HIG": "The Hartford",
	"HAS": "Hasbro",
	"HCA": "HCA Healthcare",
	"PEAK": "Healthpeak Properties",
	"HSIC": "Henry Schein",
	"HSY": "The Hershey Company",
	"HES": "Hess Corporation",
	"HPE": "Hewlett Packard Enterprise",
	"HLT": "Hilton Worldwide",
	"HOLX": "Hologic",
	"HD": "Home Depot",
	"HON": "Honeywell",
	"HRL": "Hormel",
	"HST": "Host Hotels & Resorts",
	"HWM": "Howmet Aerospace",
	"HPQ": "HP",
	"HUM": "Humana",
	"HBAN": "Huntington Bancshares",
	"HII": "Huntington Ingalls Industries",
	"IEX": "IDEX Corporation",
	"IDXX": "Idexx Laboratories",
	"INFO": "IHS Markit",
	"ITW": "Illinois Tool Works",
	"ILMN": "Illumina",
	"INCY": "Incyte",
	"IR": "Ingersoll Rand",
	"INTC": "Intel",
	"ICE": "Intercontinental Exchange",
	"IBM": "IBM",
	"IP": "International Paper",
	"IPG": "Interpublic Group",
	"IFF": "International Flavors & Fragrances",
	"INTU": "Intuit",
	"ISRG": "Intuitive Surgical",
	"IVZ": "Invesco",
	"IPGP": "IPG Photonics",
	"IQV": "IQVIA",
	"IRM": "Iron Mountain",
	"JKHY": "Jack Henry & Associates",
	"J": "Jacobs Engineering Group",
	"JBHT": "JB Hunt",
	"SJM": "JM Smucker",
	"JNJ": "Johnson & Johnson",
	"JCI": "Johnson Controls",
	"JPM": "JPMorgan Chase",
	"JNPR": "Juniper Networks",
	"KSU": "Kansas City Southern",
	"K": "Kellogg's",
	"KEY": "KeyCorp",
	"KEYS": "Keysight Technologies",
	"KMB": "Kimberly-Clark",
	"KIM": "Kimco Realty",
	"KMI": "Kinder Morgan",
	"KLAC": "KLA Corporation",
	"KHC": "Kraft Heinz",
	"KR": "Kroger",
	"LB": "L Brands",
	"LHX": "L3Harris Technologies",
	"LH": "LabCorp",
	"LRCX": "Lam Research",
	"LW": "Lamb Weston",
	"LVS": "Las Vegas Sands",
	"LEG": "Leggett & Platt",
	"LDOS": "Leidos",
	"LEN": "Lennar",
	"LLY": "Eli Lilly & Co",
	"LNC": "Lincoln National",
	"LIN": "Linde",
	"LYV": "Live Nation Entertainment",
	"LKQ": "LKQ Corporation",
	"LMT": "Lockheed Martin",
	"L": "Loews Corporation",
	"LOW": "Lowe's",
	"LUMN": "Lumen Technologies",
	"LYB": "LyondellBasell",
	"MTB": "M&T Bank",
	"MRO": "Marathon Oil",
	"MPC": "Marathon Petroleum",
	"MKTX": "MarketAxess",
	"MAR": "Marriott International",
	"MMC": "Marsh & McLennan",
	"MLM": "Martin Marietta Materials",
	"MAS": "Masco",
	"MA": "Mastercard",
	"MKC": "McCormick & Company",
	"MXIM": "Maxim Integrated",
	"MCD": "McDonald's",
	"MCK": "McKesson Corporation",
	"MDT": "Medtronic",
	"MRK": "Merck & Co",
	"MET": "MetLife",
	"MTD": "Mettler Toledo",
	"MGM": "MGM Resorts International",
	"MCHP": "Microchip Technology",
	"MU": "Micron Technology",
	"MSFT": "Microsoft",
	"MAA": "Mid-America Apartments",
	"MHK": "Mohawk Industries",
	"TAP": "Molson Coors Beverage Company",
	"MDLZ": "Mondelez International",
	"MPWR": "Monolithic Power Systems",
	"MNST": "Monster Beverage",
	"MCO": "Moody's Corporation",
	"MS": "Morgan Stanley",
	"MOS": "The Mosaic Company",
	"MSI": "Motorola Solutions",
	"MSCI": "MSCI",
	"NDAQ": "Nasdaq",
	"NTAP": "NetApp",
	"NFLX": "Netflix",
	"NWL": "Newell Brands",
	"NEM": "Newmont",
	"NWSA": "News Corp (Class A)",
	"NWS": "News Corp (Class B)",
	"NEE": "NextEra Energy",
	"NLSN": "Nielsen Holdings",
	"NKE": "Nike",
	"NI": "NiSource",
	"NSC": "Norfolk Southern",
	"NTRS": "Northern Trust",
	"NOC": "Northrop Grumman",
	"NLOK": "NortonLifeLock",
	"NCLH": "Norwegian Cruise Line Holdings",
	"NOV": "Nov",
	"NRG": "NRG Energy",
	"NUE": "Nucor",
	"NVDA": "Nvidia",
	"NVR": "NVR",
	"NXPI": "NXP",
	"ORLY": "O'Reilly Automotive",
	"OXY": "Occidental Petroleum",
	"ODFL": "Old Dominion Freight Line",
	"OMC": "Omnicom Group",
	"OKE": "Oneok",
	"ORCL": "Oracle",
	"OGN": "Organon & Co.",
	"OTIS": "Otis Worldwide",
	"PCAR": "Paccar",
	"PKG": "Packaging Corporation of America",
	"PH": "Parker-Hannifin",
	"PAYX": "Paychex",
	"PAYC": "Paycom",
	"PYPL": "PayPal",
	"PENN": "Penn National Gaming",
	"PNR": "Pentair",
	"PBCT": "People's United Financial",
	"PEP": "PepsiCo",
	"PKI": "PerkinElmer",
	"PRGO": "Perrigo",
	"PFE": "Pfizer",
	"PM": "Philip Morris International",
	"PSX": "Phillips 66",
	"PNW": "Pinnacle West Capital",
	"PXD": "Pioneer Natural Resources",
	"PNC": "PNC Financial Services",
	"POOL": "Pool Corporation",
	"PPG": "PPG Industries",
	"PPL": "PPL",
	"PFG": "Principal Financial Group",
	"PG": "Procter & Gamble",
	"PGR": "Progressive Corporation",
	"PLD": "Prologis",
	"PRU": "Prudential Financial",
	"PTC": "PTC",
	"PEG": "Public Service Enterprise Group",
	"PSA": "Public Storage",
	"PHM": "PulteGroup",
	"PVH": "PVH",
	"QRVO": "Qorvo",
	"PWR": "Quanta Services",
	"QCOM": "Qualcomm",
	"DGX": "Quest Diagnostics",
	"RL": "Ralph Lauren Corporation",
	"RJF": "Raymond James Financial",
	"RTX": "Raytheon Technologies",
	"O": "Realty Income Corporation",
	"REG": "Regency Centers",
	"REGN": "Regeneron Pharmaceuticals",
	"RF": "Regions Financial Corporation",
	"RSG": "Republic Services",
	"RMD": "ResMed",
	"RHI": "Robert Half International",
	"ROK": "Rockwell Automation",
	"ROL": "Rollins",
	"ROP": "Roper Technologies",
	"ROST": "Ross Stores",
	"RCL": "Royal Caribbean Group",
	"SPGI": "S&P Global",
	"CRM": "Salesforce",
	"SBAC": "SBA Communications",
	"SLB": "Schlumberger",
	"STX": "Seagate Technology",
	"SEE": "Sealed Air",
	"SRE": "Sempra Energy",
	"NOW": "ServiceNow",
	"SHW": "Sherwin-Williams",
	"SPG": "Simon Property Group",
	"SWKS": "Skyworks Solutions",
	"SNA": "Snap-on",
	"SO": "Southern Company",
	"LUV": "Southwest Airlines",
	"SWK": "Stanley Black & Decker",
	"SBUX": "Starbucks",
	"STT": "State Street Corporation",
	"STE": "Steris",
	"SYK": "Stryker Corporation",
	"SIVB": "SVB Financial",
	"SYF": "Synchrony Financial",
	"SNPS": "Synopsys",
	"SYY": "Sysco",
	"TMUS": "T-Mobile US",
	"TROW": "T. Rowe Price",
	"TTWO": "Take-Two Interactive",
	"TPR": "Tapestry",
	"TGT": "Target Corporation",
	"TEL": "TE Connectivity",
	"TDY": "Teledyne Technologies",
	"TFX": "Teleflex",
	"TER": "Teradyne",
	"TSLA": "Tesla",
	"TXN": "Texas Instruments",
	"TXT": "Textron",
	"TMO": "Thermo Fisher Scientific",
	"TJX": "TJX Companies",
	"TSCO": "Tractor Supply Company",
	"TT": "Trane Technologies",
	"TDG": "TransDigm Group",
	"TRV": "The Travelers Companies",
	"TRMB": "Trimble",
	"TFC": "Truist Financial",
	"TWTR": "Twitter",
	"TYL": "Tyler Technologies",
	"TSN": "Tyson Foods",
	"UDR": "UDR",
	"ULTA": "Ulta Beauty",
	"USB": "US Bancorp",
	"UAA": "Under Armour (Class A)",
	"UA": "Under Armour (Class C)",
	"UNP": "Union Pacific",
	"UAL": "United Airlines",
	"UNH": "UnitedHealth Group",
	"UPS": "United Parcel Service",
	"URI": "United Rentals",
	"UHS": "Universal Health Services",
	"UNM": "Unum Group",
	"VLO": "Valero Energy",
	"VTR": "Ventas",
	"VRSN": "Verisign",
	"VRSK": "Verisk Analytics",
	"VZ": "Verizon Communications",
	"VRTX": "Vertex Pharmaceuticals",
	"VFC": "VF Corporation",
	"VIAC": "ViacomCBS",
	"VTRS": "Viatris",
	"V": "Visa",
	"VNO": "Vornado Realty Trust",
	"VMC": "Vulcan Materials",
	"WRB": "W. R. Berkley Corporation",
	"WAB": "Wabtec",
	"WMT": "Walmart",
	"WBA": "Walgreens Boots Alliance",
	"DIS": "The Walt Disney Company",
	"WM": "Waste Management",
	"WAT": "Waters Corporation",
	"WEC": "WEC Energy Group",
	"WFC": "Wells Fargo",
	"WELL": "Welltower",
	"WST": "West Pharmaceutical Services",
	"WDC": "Western Digital",
	"WU": "Western Union",
	"WRK": "WestRock",
	"WY": "Weyerhaeuser",
	"WHR": "Whirlpool Corporation",
	"WMB": "Williams Companies",
	"WLTW": "Willis Towers Watson",
	"WYNN": "Wynn Resorts",
	"XEL": "Xcel Energy",
	"XLNX": "Xilinx",
	"XYL": "Xylem",
	"YUM": "Yum! Brands",
	"ZBRA": "Zebra Technologies",
	"ZBH": "Zimmer Biomet",
	"ZION": "Zions Bancorp",
	"ZTS": "Zoetis"
}
